### ISSUE TITLE
blackjack game 

### ISSUE THREAD

**Issue by Cypher1002** [Anamaya1729/JavaScript-Basic-Projects#114]
**Is your feature request related to a problem? Please describe.**
i can create a javascript blackjack cards game 
please assign the issue to me under hacktoberfest and please label it under hacktoberfest

**Describe the solution you'd like**
a game that is based on javascript 

**Additional context**

![blackjack](https://user-images.githubusercontent.com/92322518/194119785-41f93ad1-541b-4aba-bf23-8104f5995b58.png)

**Comment by Anamaya1729** [comment]
Create it in `easy/ ` directory. Add the appropriate readme file, reference other readme files for it.

**Comment by Cypher1002** [comment]
> Create it in `easy/ ` directory. Add the appropriate readme file, reference other readme files for it.

ok

**Comment by sumitbaroniya** [comment]
please assign me this issue

**Comment by Cypher1002** [comment]
Already pr requested for merge
