### ISSUE TITLE
Card Memory Game using JavaScript HTML and CSS

### ISSUE THREAD

**Issue by monieshravichandrran** [Anamaya1729/JavaScript-Basic-Projects#118]
Hi, I would like to contribute a simple memory game made using JavaScript under the Easy tagged JavaScript Projects.
Can you pls raise this under HacktoberFest tag?

I have attached a demo of my memory game project done using JavaScript HTML and CSS

https://user-images.githubusercontent.com/89132516/194151648-927237a4-e814-4494-bcfb-4a17a716f0f6.mp4

**Comment by monieshravichandrran** [comment]
@Anamaya1729 Thanks for assigning me

I have raised the pr for the same #119

**Comment by Anamaya1729** [comment]
Closed in #119
