### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by jblancoh** [Anamaya1729/JavaScript-Basic-Projects#14]
Hello, I would like to work on de [Weather app](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/medium/weather_app)

@Anamaya1729 @vaibhava17 
Could you assign me this app for Hacktoberfest2022?

**Comment by vaibhava17** [comment]
You can fork this repo and add your app to it and then create a pull request.
