### ISSUE TITLE
Infinite Scroll with Unsplash API

### ISSUE THREAD

**Issue by Tes-program** [Anamaya1729/JavaScript-Basic-Projects#23]
Hi, I would love to add a project called Infinite Scroll. Built with CSS,HTML and JavaScript. It fetches images from Unsplash API.

**Comment by Tes-program** [comment]
It will be under which category please @vaibhava17 @Anamaya1729

**Comment by vaibhava17** [comment]
@Tes-program you can add this project in Medium Category
