### ISSUE TITLE
Dictionary App using an API

### ISSUE THREAD

**Issue by Atharv-110** [Anamaya1729/JavaScript-Basic-Projects#4]
Hey @Anamaya1729,
I want to add an Dictionary Web App which fetches the word meaning through the dictionary API.
Also this has a feature of narration through which we can hear the word and the meaning through the speaker of the pc.
Consider this as an Contribution in Hacktoberfest 2022

**Comment by Anamaya1729** [comment]
This will be added in the medium project soon! It will be the helpful project!
