### ISSUE TITLE
GST Calculator

### ISSUE THREAD

**Issue by Anamaya1729** [Anamaya1729/JavaScript-Basic-Projects#47]
Complete this project given here [GST_Calculator](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/GST_calculator)

**Comment by Satyabrat-Ojha** [comment]
@Anamaya1729 I would like to work on this, can you please assign it me

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by vaibhava17** [comment]
whoever completes it first will get its request merge

**Comment by Anamaya1729** [comment]
Completed in #86
