### ISSUE TITLE
Color_picker_and_switcher

### ISSUE THREAD

**Issue by Anamaya1729** [Anamaya1729/JavaScript-Basic-Projects#49]
Complete this project [color_picker_and_switcher](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/color_picker_and_switcher)

**Comment by shravan2524** [comment]
@Anamaya1729 , I want to work in this, Please assign it to me.

**Comment by Anamaya1729** [comment]
@shravan2524 complete #52 first and stop spamming in issues.

**Comment by umeshchavda05** [comment]
Can i work on this as i was working on #50 but it was closed as someone else completed that
