### ISSUE TITLE
countown_with_timer

### ISSUE THREAD

**Issue by Anamaya1729** [Anamaya1729/JavaScript-Basic-Projects#50]
Complete this here : [countown_with_timer](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/countown_with_timer)

**Comment by umeshchavda05** [comment]
hey can you assign this issue to me and add the hacktoberfest label

**Comment by shravan2524** [comment]
@Anamaya1729 , Can you assign to me.

**Comment by Anamaya1729** [comment]
@shravan2524 It's already been assigned please check other issues.

**Comment by Anamaya1729** [comment]
Completed in #63
