### ISSUE TITLE
currency_convertor

### ISSUE THREAD

**Issue by Anamaya1729** [Anamaya1729/JavaScript-Basic-Projects#51]
Complete this here : [currency_convertor](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/currency_convertor)

**Comment by deepesh16b** [comment]
How i can contribute in this

**Comment by deepesh16b** [comment]
Please assign this to me

**Comment by Anamaya1729** [comment]
> How i can contribute in this

@deepesh16b read [How To Contribute](https://github.com/Anamaya1729/JavaScript-Basic-Projects/blob/master/CONTRIBUTING.md).

**Comment by sohan2503001** [comment]
Can you assign me this issue

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by rakshitdabral** [comment]
#98

**Comment by rakshitdabral** [comment]
@deepesh16b are you trying to raise PR of this project?

**Comment by deepesh16b** [comment]
> @deepesh16b are you trying to raise PR of this project?

No, I am out now

**Comment by rakshitdabral** [comment]
so your repo got merged? @deepesh16b

**Comment by deepesh16b** [comment]
> so your repo got merged? @deepesh16b 

No

**Comment by rakshitdabral** [comment]
Oh ok cool..I got merge conflicts and saw someone code was already merged.So i think this issue should be closed now
