### ISSUE TITLE
 rock_paper_scissor 

### ISSUE THREAD

**Issue by Anamaya1729** [Anamaya1729/JavaScript-Basic-Projects#54]
Complete this here : [rock_paper_scissor](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/rock_paper_scissor)

**Comment by Aryangp** [comment]
can you elaborate this issue a little more like what i have to complete in this project

**Comment by Anamaya1729** [comment]
Please check the README in [rock_paper_scissor](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/rock_paper_scissor) for details.

**Comment by ayush4345** [comment]
Hey,as I have already done this project.so,I would happy to contribute to this repo.

Assign me this issue.

**Comment by Anamaya1729** [comment]
Completed in #72.

**Comment by ayush4345** [comment]
Why this is closed ?,I need some more time to complete
