### ISSUE TITLE
 tic_tac_toe 

### ISSUE THREAD

**Issue by Anamaya1729** [Anamaya1729/JavaScript-Basic-Projects#56]
Complete this here : [tic_tac_toe](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/tic_tac_toe)

**Comment by rakshitdabral** [comment]
#57 

Here is the link for the game works perfectly fine

**Comment by rakshitdabral** [comment]
as soon as i fork your repo this is what i get 
![Screenshot (8)](https://user-images.githubusercontent.com/96056758/193745291-7b210c8a-0b79-4bc8-9619-fac8ab42147a.png)

**Comment by rakshitdabral** [comment]
you have to merge it first in master, becuase i know i am not modifying readme file in feedback directory

**Comment by rakshitdabral** [comment]
If i try to create a new branch which i will have to do, this is what i get , it counts it as i am modifying the file
![Screenshot (9)](https://user-images.githubusercontent.com/96056758/193745512-c96e54b5-3a45-4a65-bdfe-622d9c23bc52.png)

**Comment by rakshitdabral** [comment]
tell me which option i should go with

**Comment by vaibhava17** [comment]
Create a branch and then after pushing your code create a pull request

**Comment by rakshitdabral** [comment]
i know that bro

**Comment by Anamaya1729** [comment]
I have checked and there is no unmerged file. It seems like your local issue.

**Comment by rakshitdabral** [comment]
so leave the changes or bring the changes

**Comment by rakshitdabral** [comment]
as you can see i forked the repo again

**Comment by Anamaya1729** [comment]
Please follow : [CONTRIBUTING.md](https://github.com/Anamaya1729/JavaScript-Basic-Projects/blob/master/CONTRIBUTING.md)

**Comment by rakshitdabral** [comment]
i already read it, its not working as soon as i fork your repo this is what i get

**Comment by rakshitdabral** [comment]
ok so you are saying there is nothing to be merged nah, so can i discard it?

**Comment by Anamaya1729** [comment]
Yes you can. You can also create a branch. But just create a concise PR.

**Comment by rakshitdabral** [comment]
ok i will create a pull req in a min please check it

**Comment by Anamaya1729** [comment]
Please don't spam PR. This is the warning. Re-clone the Repository your issue is local. Please make sure your next PR is your final one.

**Comment by rakshitdabral** [comment]
![image](https://user-images.githubusercontent.com/96056758/193748597-23c30a0a-ec3c-4808-a063-38db5f8555d5.png)

Same named file present in this directory, please remove one of them.

**Comment by Anamaya1729** [comment]
Try now.

**Comment by rakshitdabral** [comment]
#59  
here you can check now
