### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by stuck-in-a-conundrum** [Anamaya1729/JavaScript-Basic-Projects#60]
Creating a to-do list using Javascript, HTML and CSS

**Comment by Anamaya1729** [comment]
This project is already reviewed, and completed : [to_do_list](https://github.com/Anamaya1729/JavaScript-Basic-Projects/tree/master/easy/to_do_list). Please try other projects : [good first issues](https://github.com/Anamaya1729/JavaScript-Basic-Projects/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
