### ISSUE TITLE
Wanted to add a text editor web in javascript

### ISSUE THREAD

**Issue by abhijain2003** [Anamaya1729/JavaScript-Basic-Projects#66]
Hey I Wanted to add a text editor web in javascript, please assign it to me under hacktoberfest 2022

**Comment by Anamaya1729** [comment]
Create a PR for it in easy/

**Comment by abhijain2003** [comment]
please assign this to me under hacktoberfest 2022

**Comment by Anamaya1729** [comment]
Your PR will be accepted under Hacktoberfest. It doesn't need to be assigned to you.
