### ISSUE TITLE
Animated Search Bar

### ISSUE THREAD

**Issue by Mahich123** [Anamaya1729/JavaScript-Basic-Projects#87]
I would like to add **Animated Search Bar** . Can you assign me to this ?

**Comment by vaibhava17** [comment]
Please Follow all the instructions as given in [ReadMe.md](https://github.com/Anamaya1729/JavaScript-Basic-Projects#readme).

**Comment by Mahich123** [comment]
Ok

**Comment by Mahich123** [comment]
@vaibhava17  Made pr can you check the changes ?

**Comment by vaibhava17** [comment]
ok

**Comment by Mahich123** [comment]
@vaibhava17  made the fixes as you said you can check now
